@startuml
start
:!start;
:Esperar 2000ms;
:!main;

partition "Bucle Principal (!main)" {
  if (¿Battery <= 0?) then (sí)
    :Broadcast batteryDepleted;
    :Esperar 5000ms;
  elseif (¿Battery <= DistanceToCharger?) then (sí)
    :!resetSweep;
    :!goToCharger;
  else
    partition "Operación Normal" {
      :!cleaningLoop;
      note right
        Ver lógica detallada en
        diagramaCleaningLoop.puml
      end note
      
      :!evadeOwner;
      if (¿Limit 0 reached?) then (sí)
        :!moveRandomly;
        :!reduceBattery;
      endif
    }
  endif
}

:Repetir !main;

group "Eventos Reactivos" {
  :at(robot, dirty) -> !reduceBattery, clean(robot);
  :at(robot, intruder) -> send owner unknownAgentDetected;
  :at(robot, charger) -> !resetBattery;
}

stop
@enduml
